#!/bin/bash

function usage()
{
	printf "Open a VIDEO_FILE in mplayer with a corresponding subtitle file.\n"
	printf "A name of subtitle file is gained by replacing an extension of VIDEO_FILE with the \".srt\" extension.\n"
	printf "Usage: %s VIDEO_FILE\n" "$(basename "$0")";
	exit "$1";
}

function main()
{
	if [ "$#" -ne "1" ]; then
		printf "error: a wrong number of arguments.\n"
		exit 1;
	fi

	if [ "$1" = "-h" -o "$1" = "--help" ]; then
		usage 0
	fi

	FILE="$1";
	SUB=""${FILE%.*}".srt";
	# if a subtitle file is available
	if [ -f "$SUB" ]; then
		mplayer "$FILE" -sub "$SUB";
	else
		mplayer "$FILE";
	fi
}

main "$@"
exit 0;
